tag @s[type=minecraft:husk] add undead
tag @s[type=minecraft:skeleton] add undead
tag @s[type=minecraft:skeleton_horse] add undead
tag @s[type=minecraft:stray] add undead
tag @s[type=minecraft:wither] add undead
tag @s[type=minecraft:wither_skeleton] add undead
tag @s[type=minecraft:zombie] add undead
tag @s[type=minecraft:zombie_horse] add undead
tag @s[type=minecraft:zombie_pigman] add undead
tag @s[type=minecraft:zombie_villager] add undead
tag @s add marked