execute if entity @s[scores={GoToBoss=1}] run teleport @a THECRIB
execute if entity @s[scores={GoToBoss=2}] run teleport @a THEGRAVEYARD
execute if entity @s[scores={GoToBoss=3}] run teleport @a THEBALCONY
execute if entity @s[scores={GoToBoss=4}] run teleport @a THEROOF
execute if entity @s[scores={GoToBoss=5}] run teleport @a FIREEMBLEM
execute if entity @s[scores={GoToBoss=6}] run teleport @a EPICMICKEY
execute if entity @s[scores={GoToBoss=7}] run teleport @a SMASHBROS
execute if entity @s[scores={GoToBoss=8}] run teleport @a NINJA
execute if entity @s[scores={GoToBoss=9}] run teleport @a GOLDENBOI
execute if entity @s[scores={GoToBoss=10}] run teleport @a FINALBATTLE