execute if entity @s[scores={Developer=1}] if block 771 91 7 minecraft:iron_bars run function luigis_mansion:items/key/gate
execute if entity @s[scores={Developer=1}] if block 698 113 7 minecraft:barrier run function luigis_mansion:items/key/parlor
execute if entity @s[scores={Developer=1}] if block 684 113 1 minecraft:barrier run function luigis_mansion:items/key/anteroom
execute if entity @s[scores={Developer=1}] if block 702 113 18 minecraft:barrier run function luigis_mansion:items/key/small_hallway
execute if entity @s[scores={Developer=1}] if block 698 113 55 minecraft:barrier run function luigis_mansion:items/key/master_bedroom
execute if entity @s[scores={Developer=1}] if block 706 113 44 minecraft:barrier run function luigis_mansion:items/key/nursery
execute if entity @s[scores={Developer=1}] if block 706 103 8 minecraft:barrier run function luigis_mansion:items/key/main_hallway
execute if entity @s[scores={Developer=1}] if block 691 103 -11 minecraft:barrier run function luigis_mansion:items/key/ball_room
execute if entity @s[scores={Developer=1}] if block 683 103 -38 minecraft:barrier run function luigis_mansion:items/key/storage_room
execute if entity @s[scores={Developer=1}] if block 668 103 25 minecraft:barrier run function luigis_mansion:rooms/unlock_washroom_1
execute if entity @s[scores={Developer=1}] if block 706 103 -16 minecraft:barrier run function luigis_mansion:items/key/fortune_tellers_room
execute if entity @s[scores={Developer=1}] if block 702 103 39 minecraft:barrier run function luigis_mansion:items/key/laundry_room
execute if entity @s[scores={Developer=1}] if block 664 103 14 minecraft:barrier run function luigis_mansion:items/key/conservatory
execute if entity @s[scores={Developer=1}] if block 691 103 -3 minecraft:barrier run function luigis_mansion:items/key/dining_room
execute if entity @s[scores={Developer=1}] if block 653 103 21 minecraft:barrier run function luigis_mansion:items/key/courtyard
execute if entity @s[scores={Developer=1}] if block 653 103 -41 minecraft:barrier run function luigis_mansion:items/key/rec_room
execute if entity @s[scores={Developer=1}] if block 668 103 -18 minecraft:barrier run function luigis_mansion:items/key/main_stairs
execute if entity @s[scores={Developer=1}] if block 672 103 19 minecraft:barrier run function luigis_mansion:items/key/billiards_room
execute if entity @s[scores={Developer=1}] if block 706 113 33 minecraft:barrier run function luigis_mansion:items/key/twins_room
execute if entity @s[scores={Developer=1}] if block 706 123 -23 minecraft:barrier run function luigis_mansion:items/key/safari_room
execute if entity @s[scores={Developer=1}] if block 683 123 -12 minecraft:barrier run function luigis_mansion:items/key/balcony_2
execute if entity @s[scores={Developer=1}] if block 683 123 27 minecraft:barrier run function luigis_mansion:items/key/attic_hallway_2
execute if entity @s[scores={Developer=1}] if block 698 93 -28 minecraft:barrier run function luigis_mansion:items/key/breaker_room
execute if entity @s[scores={Developer=1}] if block 706 93 -28 minecraft:barrier run function luigis_mansion:items/key/cellar
execute if entity @s[scores={Developer=1}] if block 698 123 -2 minecraft:barrier run function luigis_mansion:items/key/clockwork_room
execute if entity @s[scores={Developer=1}] if block 712 123 33 minecraft:barrier run function luigis_mansion:items/key/armory
execute if entity @s[scores={Developer=1}] if block 692 93 -15 minecraft:barrier run function luigis_mansion:items/key/pipe_room
execute if entity @s[scores={Developer=1}] if block 712 93 -15 minecraft:barrier run function luigis_mansion:items/key/cold_storage
execute if entity @s[scores={Developer=1}] if block 706 113 -16 minecraft:barrier run function luigis_mansion:items/key/sitting_room
execute if entity @s[scores={Developer=1}] if block 693 123 -18 minecraft:barrier run function luigis_mansion:items/key/artist_studio
execute if entity @s[scores={Developer=1}] if block 654 93 -19 minecraft:barrier run function luigis_mansion:items/key/secret_altar