tag @s[tag=vacuuming,type=minecraft:player] remove vacuuming
tag @s[gamemode=adventure,tag=!grabbed,nbt={Inventory:[{Slot:-106b,tag:{luigis_mansion:{id:"luigis_mansion:poltergust_3000"}}}]}] add vacuuming
execute if entity @s[tag=vacuuming,type=minecraft:player] run playsound luigis_mansion:item.poltergust.vacuuming player @a ~ ~ ~ 1
execute if entity @s[tag=vacuuming,tag=e_gadd] run playsound luigis_mansion:item.poltergust.vacuuming player @a ~ ~ ~ 1
execute if entity @s[tag=vacuuming,type=!minecraft:player] run particle minecraft:dust 0.5 0.5 0.5 1 ~0.3 ~1 ~ 0.957 0.639 0.427 1 0
execute if entity @s[tag=vacuuming,type=!minecraft:player] run particle minecraft:dust 0.5 0.5 0.5 1 ~-0.3 ~1 ~ 0.957 0.639 0.427 1 0
execute if entity @s[tag=vacuuming,type=!minecraft:player] run particle minecraft:dust 0.5 0.5 0.5 1 ~ ~1 ~0.3 0.957 0.639 0.427 1 0
execute if entity @s[tag=vacuuming,type=!minecraft:player] run particle minecraft:dust 0.5 0.5 0.5 1 ~ ~1 ~-0.3 0.957 0.639 0.427 1 0
execute if entity @s[tag=vacuuming,type=minecraft:player] run tag @e[type=minecraft:vex,distance=..20,tag=!flying] add flying
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^ ^ ^0.75 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^-0.5 ^ ^1.5 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^ ^-0.5 ^1.5 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^ ^ ^1.5 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^ ^0.5 ^1.5 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^0.5 ^ ^1.5 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^-0.5 ^ ^2.25 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^ ^-0.5 ^2.25 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^ ^ ^2.25 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^ ^0.5 ^2.25 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^0.5 ^ ^2.25 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^-0.5 ^ ^3 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^-0.5 ^ ^3 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^ ^-1 ^3 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^ ^-0.5 ^3 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^-0.5 ^-0.5 ^3 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^0.5 ^-0.5 ^3 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^ ^ ^3 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^ ^0.5 ^3 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^-0.5 ^0.5 ^3 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^0.5 ^0.5 ^3 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^ ^1 ^3 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^0.5 ^ ^3 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^1 ^ ^3 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^-1 ^ ^3.75 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^-0.5 ^ ^3.75 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^ ^-1 ^3.75 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^-0.5 ^-0.5 ^3.75 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^0.5 ^-0.5 ^3.75 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^ ^-0.5 ^3.75 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^ ^ ^3.75 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^ ^0.5 ^3.75 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^-0.5 ^0.5 ^3.75 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^0.5 ^0.5 ^3.75 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^ ^1 ^3.75 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^0.5 ^ ^3.75 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] anchored eyes run summon minecraft:area_effect_cloud ^1 ^ ^3.75 {CustomName:"{\"translate\":\"luigis_mansion:item.poltergust_3000\"}",Duration:1,Tags:["poltergust"]}
execute if entity @s[tag=vacuuming,type=minecraft:player] at @e[tag=poltergust,distance=..7] run teleport @e[type=minecraft:item,distance=..1,tag=!not_vacuumable] @s