tag @s[nbt={ActiveEffects:[{Id:1b}]}] add cheated
tag @s[nbt={ActiveEffects:[{Id:3b}]}] add cheated
tag @s[nbt={ActiveEffects:[{Id:4b}]}] add cheated
tag @s[nbt={ActiveEffects:[{Id:5b}]}] add cheated
tag @s[nbt={ActiveEffects:[{Id:6b}]}] add cheated
tag @s[nbt={ActiveEffects:[{Id:7b}]}] add cheated
tag @s[nbt={ActiveEffects:[{Id:8b}]}] add cheated
tag @s[nbt={ActiveEffects:[{Id:9b}]}] add cheated
tag @s[nbt={ActiveEffects:[{Id:10b}]}] add cheated
tag @s[tag=!resistance_lock,nbt={ActiveEffects:[{Id:11b}]}] add cheated
tag @s[nbt={ActiveEffects:[{Id:12b}]}] add cheated
tag @s[nbt={ActiveEffects:[{Id:13b}]}] add cheated
tag @s[nbt={ActiveEffects:[{Id:14b}]}] add cheated
tag @s[nbt={ActiveEffects:[{Id:15b}]}] add cheated
tag @s[gamemode=adventure,nbt={ActiveEffects:[{Id:16b}]}] add cheated
tag @s[advancements={luigis_mansion:mansion/wardrobe_room=false},nbt={ActiveEffects:[{Id:17b}]}] add cheated
tag @s[advancements={luigis_mansion:mansion/master_bedroom=true},nbt={ActiveEffects:[{Id:17b}]}] add cheated
tag @s[nbt={ActiveEffects:[{Id:18b}]}] add cheated
tag @s[nbt={ActiveEffects:[{Id:22b}]}] add cheated
tag @s[nbt={ActiveEffects:[{Id:24b}]}] add cheated
tag @s[nbt={ActiveEffects:[{Id:26b}]}] add cheated
tag @s[nbt={ActiveEffects:[{Id:27b}]}] add cheated
effect clear @s[scores={Developer=0},tag=cheated] minecraft:blindness
effect clear @s[scores={Developer=0},tag=cheated] minecraft:fire_resistance
effect clear @s[scores={Developer=0},tag=cheated] minecraft:glowing
effect clear @s[scores={Developer=0},tag=cheated] minecraft:haste
effect clear @s[scores={Developer=0},tag=cheated] minecraft:invisibility
effect clear @s[scores={Developer=0},tag=cheated] minecraft:jump_boost
effect clear @s[scores={Developer=0},tag=cheated] minecraft:luck
effect clear @s[scores={Developer=0},tag=cheated] minecraft:mining_fatigue
effect clear @s[scores={Developer=0},tag=cheated] minecraft:nausea
effect clear @s[scores={Developer=0},tag=cheated] minecraft:regeneration
effect clear @s[scores={Developer=0},tag=!grabbed] minecraft:wither
effect clear @s[scores={Developer=0},tag=cheated] minecraft:speed
effect clear @s[scores={Developer=0},tag=cheated] minecraft:strength
effect clear @s[scores={Developer=0},tag=cheated] minecraft:unluck
effect clear @s[scores={Developer=0},tag=cheated] minecraft:water_breathing
effect clear @s[scores={Developer=0},tag=cheated] minecraft:weakness
effect clear @s[scores={Developer=0},tag=cheated] minecraft:instant_health
effect clear @s[scores={Developer=0},tag=cheated] minecraft:instant_damage
effect give @s[scores={Developer=0},gamemode=creative] minecraft:night_vision 1000000 0 true
effect give @s[scores={Developer=0},gamemode=spectator] minecraft:night_vision 1000000 0 true
effect clear @s[scores={Developer=0},gamemode=adventure,tag=cheated] minecraft:night_vision
effect clear @s[scores={Developer=0},tag=cheated] minecraft:resistance
effect clear @s minecraft:hunger
effect clear @s minecraft:poison
effect give @s minecraft:saturation 1000000 0 true