scoreboard objectives add Developer dummy
scoreboard objectives add VulnerableTime dummy
scoreboard objectives add SpawnedTime dummy
scoreboard objectives add Dead deathCount
scoreboard objectives add Dead2 deathCount
scoreboard objectives add Cheating dummy
scoreboard objectives add Toad1 trigger
scoreboard objectives add Toad3 trigger
scoreboard objectives add Toad4 trigger
scoreboard objectives add Toad5 trigger
scoreboard objectives add Twins trigger
scoreboard objectives add EGadd trigger
scoreboard objectives add Melody trigger
scoreboard objectives add ClocktowerChoice trigger
scoreboard objectives add Clocktower dummy
scoreboard objectives add Boos dummy
scoreboard objectives add ClairvoyaChoice trigger
scoreboard objectives add JarvisChoice trigger
scoreboard objectives add Walk minecraft.custom:minecraft.walk_one_cm
scoreboard objectives add Run minecraft.custom:minecraft.sprint_one_cm
scoreboard objectives add Count minecraft.killed:minecraft.zombie
scoreboard objectives add Music dummy
scoreboard objectives add Dialog dummy
scoreboard objectives add MusicType dummy
scoreboard objectives add NotLookedAt dummy
scoreboard objectives add GrabbedTime dummy
scoreboard objectives add Damage minecraft.custom:minecraft.damage_taken
scoreboard objectives add TotalDamage minecraft.custom:minecraft.damage_taken
scoreboard objectives add Score dummy
scoreboard objectives add Laughing dummy
scoreboard objectives add Attempts dummy
scoreboard objectives add FlashlightTime dummy
scoreboard objectives add Attack minecraft.custom:minecraft.damage_dealt
scoreboard objectives add PlayerCount dummy
scoreboard objectives add Multiplayer dummy
scoreboard objectives add ScanTime dummy
scoreboard objectives add HeartBeat dummy
scoreboard objectives add Neville dummy
scoreboard objectives add Lydia dummy
scoreboard objectives add Chauncey dummy
scoreboard objectives add Wirlindas dummy
scoreboard objectives add Shivers dummy
scoreboard objectives add MelodyPianissima dummy
scoreboard objectives add MrLuggs dummy
scoreboard objectives add Spooky dummy
scoreboard objectives add Bogmire dummy
scoreboard objectives add BiffAtlas dummy
scoreboard objectives add Nana dummy
scoreboard objectives add MissPetunia dummy
scoreboard objectives add SlimBankshot dummy
scoreboard objectives add HenryAndOrville dummy
scoreboard objectives add MadameClairvoya dummy
scoreboard objectives add Boolossus dummy
scoreboard objectives add UncleGrimmly dummy
scoreboard objectives add ClockSoldiers dummy
scoreboard objectives add Jarvis dummy
scoreboard objectives add SuePea dummy
scoreboard objectives add SirWeston dummy
scoreboard objectives add VincentVanGore dummy
scoreboard objectives add KingBoo dummy
scoreboard objectives add GoToBoss dummy
scoreboard objectives add Offline minecraft.custom:minecraft.leave_game
team add Ghosts
team add Passive