execute if entity @s[tag=entered] run tag @a[tag=!entered] add entered
execute if entity @s[tag=toad_1] run tag @a[tag=!toad_1] add toad_1
execute if entity @s[tag=toad_2] run tag @a[tag=!toad_2] add toad_2
execute if entity @s[tag=toad_3] run tag @a[tag=!toad_3] add toad_3
execute if entity @s[tag=toad_4] run tag @a[tag=!toad_4] add toad_4
execute if entity @s[tag=toad_5] run tag @a[tag=!toad_5] add toad_5
execute if entity @s[tag=met_e_gadd] run tag @a[tag=!met_e_gadd] add met_e_gadd
execute if entity @s[tag=fire_element] run tag @a[tag=!fire_element] add fire_element
execute if entity @s[tag=water_element] run tag @a[tag=!water_element] add water_element
execute if entity @s[tag=ice_element] run tag @a[tag=!ice_element] add ice_element
execute if entity @s[tag=walhart] run tag @a[tag=!walhart] add walhart
execute if entity @s[tag=clocktower] run tag @a[tag=!clocktower] add clocktower
execute if entity @s[tag=skoul] run tag @a[tag=!skoul] add skoul
execute if entity @s[tag=master_hand_and_crazy_hand] run tag @a[tag=!master_hand_and_crazy_hand] add master_hand_and_crazy_hand
execute if entity @s[tag=ninjamaster] run tag @a[tag=!ninjamaster] add ninjamaster
execute if entity @s[tag=ultimategold] run tag @a[tag=!ultimategold] add ultimategold
execute if entity @s[tag=fvbico] run tag @a[tag=!fvbico] add fvbico
