execute if block 698 113 7 minecraft:barrier if block 699 113 8 minecraft:jungle_door[open=true] run summon minecraft:area_effect_cloud 699 112 8 {Duration:101,CustomName:"{\"translate\":\"luigis_mansion:entity.door\"}",Tags:["door","jungle_door","west","left"]}
execute if block 698 113 7 minecraft:barrier if block 699 113 8 minecraft:jungle_door[open=true] if entity @a[tag=!entered,limit=1] run summon minecraft:zombie 713 104 8.0 {CustomName:"{\"translate\":\"luigis_mansion:entity.gold_ghost\"}",CustomNameVisible:1b,Invulnerable:1b,NoAI:1b,NoGravity:1b,ArmorItems:[{},{},{},{id:"minecraft:brick",Count:1b,tag:{luigis_mansion:{id:"luigis_mansion:key",key:"parlor"},display:{Name:"{\"translate\":\"luigis_mansion:item.key\",\"with\":[{\"translate\":\"luigis_mansion:location.parlor\"}]}"}}}],Silent:1b,DeathLootTable:"luigis_mansion:entities/ghosts/gold_ghost",Health:1.0f,Attributes:[{Name:"generic.maxHealth",Base:1.0d},{Name:"generic.movementSpeed",Base:0.0d},{Name:"generic.followRange",Base:20.0d},{Name:"generic.knockbackResistance",Base:0.0d},{Name:"generic.armor",Base:0.0d},{Name:"generic.armorToughness",Base:0.0d},{Name:"generic.attackDamage",Base:10.0d},{Name:"zombie.spawnReinforcements",Base:0.0d}],ActiveEffects:[{Id:14b,Duration:1000000,Ambient:1b,ShowParticles:0b,Amplifier:0b}],HandDropChances:[1.0f,1.0f],ArmorDropChances:[0.0f,0.0f,0.0f,0.0f],PersistenceRequired:1b,LeftHanded:1b,Team:"Ghosts",Tags:["normal_enemy","foyer","vacuuming"]}
execute if block 698 113 7 minecraft:barrier if block 699 113 8 minecraft:jungle_door[open=true] if entity @a[tag=!entered,limit=1] run tag @a add entered
execute if block 698 113 7 minecraft:barrier if block 699 113 7 minecraft:jungle_door[open=true] run summon minecraft:area_effect_cloud 699 112 7 {Duration:101,CustomName:"{\"translate\":\"luigis_mansion:entity.door\"}",Tags:["door","jungle_door","west","right"]}
execute if block 698 113 7 minecraft:barrier if block 699 113 7 minecraft:jungle_door[open=true] if entity @a[tag=!entered,limit=1] run summon minecraft:zombie 713 104 8.0 {CustomName:"{\"translate\":\"luigis_mansion:entity.gold_ghost\"}",CustomNameVisible:1b,Invulnerable:1b,NoAI:1b,NoGravity:1b,ArmorItems:[{},{},{},{id:"minecraft:brick",Count:1b,tag:{luigis_mansion:{id:"luigis_mansion:key",key:"parlor"},display:{Name:"{\"translate\":\"luigis_mansion:item.key\",\"with\":[{\"translate\":\"luigis_mansion:location.parlor\"}]}"}}}],Silent:1b,DeathLootTable:"luigis_mansion:entities/ghosts/gold_ghost",Health:1.0f,Attributes:[{Name:"generic.maxHealth",Base:1.0d},{Name:"generic.movementSpeed",Base:0.0d},{Name:"generic.followRange",Base:20.0d},{Name:"generic.knockbackResistance",Base:0.0d},{Name:"generic.armor",Base:0.0d},{Name:"generic.armorToughness",Base:0.0d},{Name:"generic.attackDamage",Base:10.0d},{Name:"zombie.spawnReinforcements",Base:0.0d}],ActiveEffects:[{Id:14b,Duration:1000000,Ambient:1b,ShowParticles:0b,Amplifier:0b}],HandDropChances:[1.0f,1.0f],ArmorDropChances:[0.0f,0.0f,0.0f,0.0f],PersistenceRequired:1b,LeftHanded:1b,Team:"Ghosts",Tags:["normal_enemy","foyer","vacuuming"]}
execute if block 698 113 7 minecraft:barrier if block 699 113 7 minecraft:jungle_door[open=true] if entity @a[tag=!entered,limit=1] run tag @a add entered
execute if block 684 113 1 minecraft:barrier if block 685 113 1 minecraft:dark_oak_door[open=true] run summon minecraft:area_effect_cloud 685 112 1 {Duration:101,CustomName:"{\"translate\":\"luigis_mansion:entity.door\"}",Tags:["door","dark_oak_door","west","right"]}
execute if block 702 113 18 minecraft:barrier if block 702 113 17 minecraft:dark_oak_door[open=true] run summon minecraft:area_effect_cloud 702 112 17 {Duration:101,CustomName:"{\"translate\":\"luigis_mansion:entity.door\"}",Tags:["door","dark_oak_door","south","left"]}
execute if block 698 113 55 minecraft:barrier if block 699 113 55 minecraft:dark_oak_door[open=true] run summon minecraft:area_effect_cloud 699 112 55 {Duration:101,CustomName:"{\"translate\":\"luigis_mansion:entity.door\"}",Tags:["door","dark_oak_door","west","right"]}
execute if block 706 113 44 minecraft:barrier if block 705 113 44 minecraft:dark_oak_door[open=true] run summon minecraft:area_effect_cloud 705 112 44 {Duration:101,CustomName:"{\"translate\":\"luigis_mansion:entity.door\"}",Tags:["door","dark_oak_door","east","left"]}
execute if block 691 103 -11 minecraft:barrier if block 691 103 -10 minecraft:dark_oak_door[open=true] run summon minecraft:area_effect_cloud 691 102 -10 {Duration:101,CustomName:"{\"translate\":\"luigis_mansion:entity.door\"}",Tags:["door","dark_oak_door","north","right"]}
execute if block 683 103 -38 minecraft:barrier if block 684 103 -38 minecraft:dark_oak_door[open=true] run summon minecraft:area_effect_cloud 684 102 -38 {Duration:101,CustomName:"{\"translate\":\"luigis_mansion:entity.door\"}",Tags:["door","dark_oak_door","west","right"]}
execute if block 668 103 25 minecraft:barrier if block 668 103 24 minecraft:dark_oak_door[open=true] run tag @a[sort=nearest,gamemode=adventure,scores={Dialog=0}] add locked_washroom
execute if block 668 103 25 minecraft:barrier if block 668 103 24 minecraft:dark_oak_door[open=true] run summon minecraft:area_effect_cloud 668 102 24 {Duration:101,CustomName:"{\"translate\":\"luigis_mansion:entity.door\"}",Tags:["door","dark_oak_door","south","left"]}
execute if block 706 103 -16 minecraft:barrier if block 705 103 -16 minecraft:dark_oak_door[open=true] run summon minecraft:area_effect_cloud 705 102 -16 {Duration:101,CustomName:"{\"translate\":\"luigis_mansion:entity.door\"}",Tags:["door","dark_oak_door","east","left"]}
execute if block 702 103 39 minecraft:barrier if block 702 103 38 minecraft:dark_oak_door[open=true] run summon minecraft:area_effect_cloud 702 102 38 {Duration:101,CustomName:"{\"translate\":\"luigis_mansion:entity.door\"}",Tags:["door","dark_oak_door","south","left"]}
execute if block 664 103 14 minecraft:barrier if block 665 103 14 minecraft:dark_oak_door[open=true] run summon minecraft:area_effect_cloud 665 102 14 {Duration:101,CustomName:"{\"translate\":\"luigis_mansion:entity.door\"}",Tags:["door","dark_oak_door","west","right"]}
execute if block 691 103 -3 minecraft:barrier if block 691 103 -4 minecraft:dark_oak_door[open=true] run summon minecraft:area_effect_cloud 691 102 -4 {Duration:101,CustomName:"{\"translate\":\"luigis_mansion:entity.door\"}",Tags:["door","dark_oak_door","south","left"]}
execute if block 653 103 -41 minecraft:barrier if block 652 103 -41 minecraft:dark_oak_door[open=true] run summon minecraft:area_effect_cloud 652 102 -41 {Duration:101,CustomName:"{\"translate\":\"luigis_mansion:entity.door\"}",Tags:["door","dark_oak_door","east","left"]}
execute if block 668 103 -18 minecraft:barrier if block 668 103 -17 minecraft:dark_oak_door[open=true] run summon minecraft:area_effect_cloud 668 102 -17 {Duration:101,CustomName:"{\"translate\":\"luigis_mansion:entity.door\"}",Tags:["door","dark_oak_door","north","right"]}
execute if block 668 103 -18 minecraft:barrier if block 668 103 -19 minecraft:dark_oak_door[open=true] run summon minecraft:area_effect_cloud 668 102 -19 {Duration:101,CustomName:"{\"translate\":\"luigis_mansion:entity.door\"}",Tags:["door","dark_oak_door","south","left"]}
execute if block 672 103 19 minecraft:barrier if block 671 103 19 minecraft:dark_oak_door[open=true] run summon minecraft:area_effect_cloud 671 102 19 {Duration:101,CustomName:"{\"translate\":\"luigis_mansion:entity.door\"}",Tags:["door","dark_oak_door","east","left"]}
execute if block 706 113 33 minecraft:barrier if block 705 113 33 minecraft:dark_oak_door[open=true] run summon minecraft:area_effect_cloud 705 112 33 {Duration:101,CustomName:"{\"translate\":\"luigis_mansion:entity.door\"}",Tags:["door","dark_oak_door","east","left"]}
execute if block 706 123 -23 minecraft:barrier if block 705 123 -23 minecraft:oak_door[open=true] run summon minecraft:area_effect_cloud 705 122 -23 {Duration:101,CustomName:"{\"translate\":\"luigis_mansion:entity.door\"}",Tags:["door","oak_door","east","left"]}
execute if block 683 123 -12 minecraft:barrier if block 684 123 -12 minecraft:oak_door[open=true] run summon minecraft:area_effect_cloud 684 122 -12 {Duration:101,CustomName:"{\"translate\":\"luigis_mansion:entity.door\"}",Tags:["door","oak_door","west","right"]}
execute if block 698 93 -28 minecraft:barrier if block 699 93 -28 minecraft:oak_door[open=true] run summon minecraft:area_effect_cloud 699 92 -28 {Duration:101,CustomName:"{\"translate\":\"luigis_mansion:entity.door\"}",Tags:["door","oak_door","west","right"]}
execute if block 706 93 -28 minecraft:barrier if block 705 93 -28 minecraft:oak_door[open=true] run summon minecraft:area_effect_cloud 705 92 -28 {Duration:101,CustomName:"{\"translate\":\"luigis_mansion:entity.door\"}",Tags:["door","oak_door","east","left"]}
execute if block 698 123 -2 minecraft:barrier if block 699 123 -2 minecraft:oak_door[open=true] run summon minecraft:area_effect_cloud 699 122 -2 {Duration:101,CustomName:"{\"translate\":\"luigis_mansion:entity.door\"}",Tags:["door","oak_door","west","right"]}
execute if block 712 123 33 minecraft:barrier if block 712 123 32 minecraft:oak_door[open=true] run summon minecraft:area_effect_cloud 712 122 32 {Duration:101,CustomName:"{\"translate\":\"luigis_mansion:entity.door\"}",Tags:["door","oak_door","south","left"]}
execute if block 692 93 -15 minecraft:barrier if block 692 93 -16 minecraft:oak_door[open=true] run summon minecraft:area_effect_cloud 692 92 -16 {Duration:101,CustomName:"{\"translate\":\"luigis_mansion:entity.door\"}",Tags:["door","oak_door","south","left"]}
execute if block 712 93 -15 minecraft:barrier if block 712 93 -16 minecraft:oak_door[open=true] run summon minecraft:area_effect_cloud 712 92 -16 {Duration:101,CustomName:"{\"translate\":\"luigis_mansion:entity.door\"}",Tags:["door","oak_door","south","left"]}
execute if block 706 113 -16 minecraft:barrier if block 705 113 -16 minecraft:dark_oak_door[open=true] run summon minecraft:area_effect_cloud 705 112 -16 {Duration:101,CustomName:"{\"translate\":\"luigis_mansion:entity.door\"}",Tags:["door","dark_oak_door","east","left"]}
execute if block 693 123 -18 minecraft:barrier if block 693 123 -17 minecraft:oak_door[open=true] run summon minecraft:area_effect_cloud 693 122 -17 {Duration:101,CustomName:"{\"translate\":\"luigis_mansion:entity.door\"}",Tags:["door","oak_door","north","right"]}