scoreboard players add @s NotLookedAt 1
execute if entity @s[scores={NotLookedAt=1}] run playsound luigis_mansion:block.door.locked neutral @a ~ ~1 ~ 1
execute if entity @s[scores={NotLookedAt=2..}] run kill @e[distance=..1,tag=door,scores={NotLookedAt=1}]
execute if entity @s[tag=acacia_door,tag=east,tag=left] run setblock ~ ~ ~ minecraft:acacia_door[half=lower,facing=east,hinge=left,open=false,powered=false]
execute if entity @s[tag=acacia_door,tag=east,tag=left] run setblock ~ ~1 ~ minecraft:acacia_door[half=upper,facing=east,hinge=left,open=false,powered=false]
execute if entity @s[tag=acacia_door,tag=east,tag=right] run setblock ~ ~ ~ minecraft:acacia_door[half=lower,facing=east,hinge=right,open=false,powered=false]
execute if entity @s[tag=acacia_door,tag=east,tag=right] run setblock ~ ~1 ~ minecraft:acacia_door[half=upper,facing=east,hinge=right,open=false,powered=false]
execute if entity @s[tag=acacia_door,tag=north,tag=left] run setblock ~ ~ ~ minecraft:acacia_door[half=lower,facing=north,hinge=left,open=false,powered=false]
execute if entity @s[tag=acacia_door,tag=north,tag=left] run setblock ~ ~1 ~ minecraft:acacia_door[half=upper,facing=north,hinge=left,open=false,powered=false]
execute if entity @s[tag=acacia_door,tag=north,tag=right] run setblock ~ ~ ~ minecraft:acacia_door[half=lower,facing=north,hinge=right,open=false,powered=false]
execute if entity @s[tag=acacia_door,tag=north,tag=right] run setblock ~ ~1 ~ minecraft:acacia_door[half=upper,facing=north,hinge=right,open=false,powered=false]
execute if entity @s[tag=acacia_door,tag=south,tag=left] run setblock ~ ~ ~ minecraft:acacia_door[half=lower,facing=south,hinge=left,open=false,powered=false]
execute if entity @s[tag=acacia_door,tag=south,tag=left] run setblock ~ ~1 ~ minecraft:acacia_door[half=upper,facing=south,hinge=left,open=false,powered=false]
execute if entity @s[tag=acacia_door,tag=south,tag=right] run setblock ~ ~ ~ minecraft:acacia_door[half=lower,facing=south,hinge=right,open=false,powered=false]
execute if entity @s[tag=acacia_door,tag=south,tag=right] run setblock ~ ~1 ~ minecraft:acacia_door[half=upper,facing=south,hinge=right,open=false,powered=false]
execute if entity @s[tag=acacia_door,tag=west,tag=left] run setblock ~ ~ ~ minecraft:acacia_door[half=lower,facing=west,hinge=left,open=false,powered=false]
execute if entity @s[tag=acacia_door,tag=west,tag=left] run setblock ~ ~1 ~ minecraft:acacia_door[half=upper,facing=west,hinge=left,open=false,powered=false]
execute if entity @s[tag=acacia_door,tag=west,tag=right] run setblock ~ ~ ~ minecraft:acacia_door[half=lower,facing=west,hinge=right,open=false,powered=false]
execute if entity @s[tag=acacia_door,tag=west,tag=right] run setblock ~ ~1 ~ minecraft:acacia_door[half=upper,facing=west,hinge=right,open=false,powered=false]
execute if entity @s[tag=birch_door,tag=east,tag=left] run setblock ~ ~ ~ minecraft:birch_door[half=lower,facing=east,hinge=left,open=false,powered=false]
execute if entity @s[tag=birch_door,tag=east,tag=left] run setblock ~ ~1 ~ minecraft:birch_door[half=upper,facing=east,hinge=left,open=false,powered=false]
execute if entity @s[tag=birch_door,tag=east,tag=right] run setblock ~ ~ ~ minecraft:birch_door[half=lower,facing=east,hinge=right,open=false,powered=false]
execute if entity @s[tag=birch_door,tag=east,tag=right] run setblock ~ ~1 ~ minecraft:birch_door[half=upper,facing=east,hinge=right,open=false,powered=false]
execute if entity @s[tag=birch_door,tag=north,tag=left] run setblock ~ ~ ~ minecraft:birch_door[half=lower,facing=north,hinge=left,open=false,powered=false]
execute if entity @s[tag=birch_door,tag=north,tag=left] run setblock ~ ~1 ~ minecraft:birch_door[half=upper,facing=north,hinge=left,open=false,powered=false]
execute if entity @s[tag=birch_door,tag=north,tag=right] run setblock ~ ~ ~ minecraft:birch_door[half=lower,facing=north,hinge=right,open=false,powered=false]
execute if entity @s[tag=birch_door,tag=north,tag=right] run setblock ~ ~1 ~ minecraft:birch_door[half=upper,facing=north,hinge=right,open=false,powered=false]
execute if entity @s[tag=birch_door,tag=south,tag=left] run setblock ~ ~ ~ minecraft:birch_door[half=lower,facing=south,hinge=left,open=false,powered=false]
execute if entity @s[tag=birch_door,tag=south,tag=left] run setblock ~ ~1 ~ minecraft:birch_door[half=upper,facing=south,hinge=left,open=false,powered=false]
execute if entity @s[tag=birch_door,tag=south,tag=right] run setblock ~ ~ ~ minecraft:birch_door[half=lower,facing=south,hinge=right,open=false,powered=false]
execute if entity @s[tag=birch_door,tag=south,tag=right] run setblock ~ ~1 ~ minecraft:birch_door[half=upper,facing=south,hinge=right,open=false,powered=false]
execute if entity @s[tag=birch_door,tag=west,tag=left] run setblock ~ ~ ~ minecraft:birch_door[half=lower,facing=west,hinge=left,open=false,powered=false]
execute if entity @s[tag=birch_door,tag=west,tag=left] run setblock ~ ~1 ~ minecraft:birch_door[half=upper,facing=west,hinge=left,open=false,powered=false]
execute if entity @s[tag=birch_door,tag=west,tag=right] run setblock ~ ~ ~ minecraft:birch_door[half=lower,facing=west,hinge=right,open=false,powered=false]
execute if entity @s[tag=birch_door,tag=west,tag=right] run setblock ~ ~1 ~ minecraft:birch_door[half=upper,facing=west,hinge=right,open=false,powered=false]
execute if entity @s[tag=dark_oak_door,tag=east,tag=left] run setblock ~ ~ ~ minecraft:dark_oak_door[half=lower,facing=east,hinge=left,open=false,powered=false]
execute if entity @s[tag=dark_oak_door,tag=east,tag=left] run setblock ~ ~1 ~ minecraft:dark_oak_door[half=upper,facing=east,hinge=left,open=false,powered=false]
execute if entity @s[tag=dark_oak_door,tag=east,tag=right] run setblock ~ ~ ~ minecraft:dark_oak_door[half=lower,facing=east,hinge=right,open=false,powered=false]
execute if entity @s[tag=dark_oak_door,tag=east,tag=right] run setblock ~ ~1 ~ minecraft:dark_oak_door[half=upper,facing=east,hinge=right,open=false,powered=false]
execute if entity @s[tag=dark_oak_door,tag=north,tag=left] run setblock ~ ~ ~ minecraft:dark_oak_door[half=lower,facing=north,hinge=left,open=false,powered=false]
execute if entity @s[tag=dark_oak_door,tag=north,tag=left] run setblock ~ ~1 ~ minecraft:dark_oak_door[half=upper,facing=north,hinge=left,open=false,powered=false]
execute if entity @s[tag=dark_oak_door,tag=north,tag=right] run setblock ~ ~ ~ minecraft:dark_oak_door[half=lower,facing=north,hinge=right,open=false,powered=false]
execute if entity @s[tag=dark_oak_door,tag=north,tag=right] run setblock ~ ~1 ~ minecraft:dark_oak_door[half=upper,facing=north,hinge=right,open=false,powered=false]
execute if entity @s[tag=dark_oak_door,tag=south,tag=left] run setblock ~ ~ ~ minecraft:dark_oak_door[half=lower,facing=south,hinge=left,open=false,powered=false]
execute if entity @s[tag=dark_oak_door,tag=south,tag=left] run setblock ~ ~1 ~ minecraft:dark_oak_door[half=upper,facing=south,hinge=left,open=false,powered=false]
execute if entity @s[tag=dark_oak_door,tag=south,tag=right] run setblock ~ ~ ~ minecraft:dark_oak_door[half=lower,facing=south,hinge=right,open=false,powered=false]
execute if entity @s[tag=dark_oak_door,tag=south,tag=right] run setblock ~ ~1 ~ minecraft:dark_oak_door[half=upper,facing=south,hinge=right,open=false,powered=false]
execute if entity @s[tag=dark_oak_door,tag=west,tag=left] run setblock ~ ~ ~ minecraft:dark_oak_door[half=lower,facing=west,hinge=left,open=false,powered=false]
execute if entity @s[tag=dark_oak_door,tag=west,tag=left] run setblock ~ ~1 ~ minecraft:dark_oak_door[half=upper,facing=west,hinge=left,open=false,powered=false]
execute if entity @s[tag=dark_oak_door,tag=west,tag=right] run setblock ~ ~ ~ minecraft:dark_oak_door[half=lower,facing=west,hinge=right,open=false,powered=false]
execute if entity @s[tag=dark_oak_door,tag=west,tag=right] run setblock ~ ~1 ~ minecraft:dark_oak_door[half=upper,facing=west,hinge=right,open=false,powered=false]
execute if entity @s[tag=jungle_door,tag=east,tag=left] run setblock ~ ~ ~ minecraft:jungle_door[half=lower,facing=east,hinge=left,open=false,powered=false]
execute if entity @s[tag=jungle_door,tag=east,tag=left] run setblock ~ ~1 ~ minecraft:jungle_door[half=upper,facing=east,hinge=left,open=false,powered=false]
execute if entity @s[tag=jungle_door,tag=east,tag=right] run setblock ~ ~ ~ minecraft:jungle_door[half=lower,facing=east,hinge=right,open=false,powered=false]
execute if entity @s[tag=jungle_door,tag=east,tag=right] run setblock ~ ~1 ~ minecraft:jungle_door[half=upper,facing=east,hinge=right,open=false,powered=false]
execute if entity @s[tag=jungle_door,tag=north,tag=left] run setblock ~ ~ ~ minecraft:jungle_door[half=lower,facing=north,hinge=left,open=false,powered=false]
execute if entity @s[tag=jungle_door,tag=north,tag=left] run setblock ~ ~1 ~ minecraft:jungle_door[half=upper,facing=north,hinge=left,open=false,powered=false]
execute if entity @s[tag=jungle_door,tag=north,tag=right] run setblock ~ ~ ~ minecraft:jungle_door[half=lower,facing=north,hinge=right,open=false,powered=false]
execute if entity @s[tag=jungle_door,tag=north,tag=right] run setblock ~ ~1 ~ minecraft:jungle_door[half=upper,facing=north,hinge=right,open=false,powered=false]
execute if entity @s[tag=jungle_door,tag=south,tag=left] run setblock ~ ~ ~ minecraft:jungle_door[half=lower,facing=south,hinge=left,open=false,powered=false]
execute if entity @s[tag=jungle_door,tag=south,tag=left] run setblock ~ ~1 ~ minecraft:jungle_door[half=upper,facing=south,hinge=left,open=false,powered=false]
execute if entity @s[tag=jungle_door,tag=south,tag=right] run setblock ~ ~ ~ minecraft:jungle_door[half=lower,facing=south,hinge=right,open=false,powered=false]
execute if entity @s[tag=jungle_door,tag=south,tag=right] run setblock ~ ~1 ~ minecraft:jungle_door[half=upper,facing=south,hinge=right,open=false,powered=false]
execute if entity @s[tag=jungle_door,tag=west,tag=left] run setblock ~ ~ ~ minecraft:jungle_door[half=lower,facing=west,hinge=left,open=false,powered=false]
execute if entity @s[tag=jungle_door,tag=west,tag=left] run setblock ~ ~1 ~ minecraft:jungle_door[half=upper,facing=west,hinge=left,open=false,powered=false]
execute if entity @s[tag=jungle_door,tag=west,tag=right] run setblock ~ ~ ~ minecraft:jungle_door[half=lower,facing=west,hinge=right,open=false,powered=false]
execute if entity @s[tag=jungle_door,tag=west,tag=right] run setblock ~ ~1 ~ minecraft:jungle_door[half=upper,facing=west,hinge=right,open=false,powered=false]
execute if entity @s[tag=oak_door,tag=east,tag=left] run setblock ~ ~ ~ minecraft:oak_door[half=lower,facing=east,hinge=left,open=false,powered=false]
execute if entity @s[tag=oak_door,tag=east,tag=left] run setblock ~ ~1 ~ minecraft:oak_door[half=upper,facing=east,hinge=left,open=false,powered=false]
execute if entity @s[tag=oak_door,tag=east,tag=right] run setblock ~ ~ ~ minecraft:oak_door[half=lower,facing=east,hinge=right,open=false,powered=false]
execute if entity @s[tag=oak_door,tag=east,tag=right] run setblock ~ ~1 ~ minecraft:oak_door[half=upper,facing=east,hinge=right,open=false,powered=false]
execute if entity @s[tag=oak_door,tag=north,tag=left] run setblock ~ ~ ~ minecraft:oak_door[half=lower,facing=north,hinge=left,open=false,powered=false]
execute if entity @s[tag=oak_door,tag=north,tag=left] run setblock ~ ~1 ~ minecraft:oak_door[half=upper,facing=north,hinge=left,open=false,powered=false]
execute if entity @s[tag=oak_door,tag=north,tag=right] run setblock ~ ~ ~ minecraft:oak_door[half=lower,facing=north,hinge=right,open=false,powered=false]
execute if entity @s[tag=oak_door,tag=north,tag=right] run setblock ~ ~1 ~ minecraft:oak_door[half=upper,facing=north,hinge=right,open=false,powered=false]
execute if entity @s[tag=oak_door,tag=south,tag=left] run setblock ~ ~ ~ minecraft:oak_door[half=lower,facing=south,hinge=left,open=false,powered=false]
execute if entity @s[tag=oak_door,tag=south,tag=left] run setblock ~ ~1 ~ minecraft:oak_door[half=upper,facing=south,hinge=left,open=false,powered=false]
execute if entity @s[tag=oak_door,tag=south,tag=right] run setblock ~ ~ ~ minecraft:oak_door[half=lower,facing=south,hinge=right,open=false,powered=false]
execute if entity @s[tag=oak_door,tag=south,tag=right] run setblock ~ ~1 ~ minecraft:oak_door[half=upper,facing=south,hinge=right,open=false,powered=false]
execute if entity @s[tag=oak_door,tag=west,tag=left] run setblock ~ ~ ~ minecraft:oak_door[half=lower,facing=west,hinge=left,open=false,powered=false]
execute if entity @s[tag=oak_door,tag=west,tag=left] run setblock ~ ~1 ~ minecraft:oak_door[half=upper,facing=west,hinge=left,open=false,powered=false]
execute if entity @s[tag=oak_door,tag=west,tag=right] run setblock ~ ~ ~ minecraft:oak_door[half=lower,facing=west,hinge=right,open=false,powered=false]
execute if entity @s[tag=oak_door,tag=west,tag=right] run setblock ~ ~1 ~ minecraft:oak_door[half=upper,facing=west,hinge=right,open=false,powered=false]
execute if entity @s[tag=spruce_door,tag=east,tag=left] run setblock ~ ~ ~ minecraft:spruce_door[half=lower,facing=east,hinge=left,open=false,powered=false]
execute if entity @s[tag=spruce_door,tag=east,tag=left] run setblock ~ ~1 ~ minecraft:spruce_door[half=upper,facing=east,hinge=left,open=false,powered=false]
execute if entity @s[tag=spruce_door,tag=east,tag=right] run setblock ~ ~ ~ minecraft:spruce_door[half=lower,facing=east,hinge=right,open=false,powered=false]
execute if entity @s[tag=spruce_door,tag=east,tag=right] run setblock ~ ~1 ~ minecraft:spruce_door[half=upper,facing=east,hinge=right,open=false,powered=false]
execute if entity @s[tag=spruce_door,tag=north,tag=left] run setblock ~ ~ ~ minecraft:spruce_door[half=lower,facing=north,hinge=left,open=false,powered=false]
execute if entity @s[tag=spruce_door,tag=north,tag=left] run setblock ~ ~1 ~ minecraft:spruce_door[half=upper,facing=north,hinge=left,open=false,powered=false]
execute if entity @s[tag=spruce_door,tag=north,tag=right] run setblock ~ ~ ~ minecraft:spruce_door[half=lower,facing=north,hinge=right,open=false,powered=false]
execute if entity @s[tag=spruce_door,tag=north,tag=right] run setblock ~ ~1 ~ minecraft:spruce_door[half=upper,facing=north,hinge=right,open=false,powered=false]
execute if entity @s[tag=spruce_door,tag=south,tag=left] run setblock ~ ~ ~ minecraft:spruce_door[half=lower,facing=south,hinge=left,open=false,powered=false]
execute if entity @s[tag=spruce_door,tag=south,tag=left] run setblock ~ ~1 ~ minecraft:spruce_door[half=upper,facing=south,hinge=left,open=false,powered=false]
execute if entity @s[tag=spruce_door,tag=south,tag=right] run setblock ~ ~ ~ minecraft:spruce_door[half=lower,facing=south,hinge=right,open=false,powered=false]
execute if entity @s[tag=spruce_door,tag=south,tag=right] run setblock ~ ~1 ~ minecraft:spruce_door[half=upper,facing=south,hinge=right,open=false,powered=false]
execute if entity @s[tag=spruce_door,tag=west,tag=left] run setblock ~ ~ ~ minecraft:spruce_door[half=lower,facing=west,hinge=left,open=false,powered=false]
execute if entity @s[tag=spruce_door,tag=west,tag=left] run setblock ~ ~1 ~ minecraft:spruce_door[half=upper,facing=west,hinge=left,open=false,powered=false]
execute if entity @s[tag=spruce_door,tag=west,tag=right] run setblock ~ ~ ~ minecraft:spruce_door[half=lower,facing=west,hinge=right,open=false,powered=false]
execute if entity @s[tag=spruce_door,tag=west,tag=right] run setblock ~ ~1 ~ minecraft:spruce_door[half=upper,facing=west,hinge=right,open=false,powered=false]
execute if entity @s[scores={NotLookedAt=40},tag=east] run clone ~2 ~ ~ ~2 ~1 ~ ~-1 ~ ~
execute if entity @s[scores={NotLookedAt=45},tag=east] run fill ~-1 ~ ~ ~-1 ~1 ~ minecraft:air
execute if entity @s[scores={NotLookedAt=50},tag=east] run clone ~2 ~ ~ ~2 ~1 ~ ~-1 ~ ~
execute if entity @s[scores={NotLookedAt=55},tag=east] run fill ~-1 ~ ~ ~-1 ~1 ~ minecraft:air
execute if entity @s[scores={NotLookedAt=40},tag=north] run clone ~ ~ ~-2 ~ ~1 ~-2 ~ ~ ~1
execute if entity @s[scores={NotLookedAt=45},tag=north] run fill ~ ~ ~1 ~ ~1 ~1 minecraft:air
execute if entity @s[scores={NotLookedAt=50},tag=north] run clone ~ ~ ~-2 ~ ~1 ~-2 ~ ~ ~1
execute if entity @s[scores={NotLookedAt=55},tag=north] run fill ~ ~ ~1 ~ ~1 ~1 minecraft:air
execute if entity @s[scores={NotLookedAt=40},tag=south] run clone ~ ~ ~2 ~ ~1 ~2 ~ ~ ~-1
execute if entity @s[scores={NotLookedAt=45},tag=south] run fill ~ ~ ~-1 ~ ~1 ~-1 minecraft:air
execute if entity @s[scores={NotLookedAt=50},tag=south] run clone ~ ~ ~2 ~ ~1 ~2 ~ ~ ~-1
execute if entity @s[scores={NotLookedAt=55},tag=south] run fill ~ ~ ~-1 ~ ~1 ~-1 minecraft:air
execute if entity @s[scores={NotLookedAt=40},tag=west] run clone ~-2 ~ ~ ~-2 ~1 ~ ~1 ~ ~
execute if entity @s[scores={NotLookedAt=45},tag=west] run fill ~1 ~ ~ ~1 ~1 ~ minecraft:air
execute if entity @s[scores={NotLookedAt=50},tag=west] run clone ~-2 ~ ~ ~-2 ~1 ~ ~1 ~ ~
execute if entity @s[scores={NotLookedAt=55},tag=west] run fill ~1 ~ ~ ~1 ~1 ~ minecraft:air
kill @s[scores={NotLookedAt=60}]