execute if entity @s[x=698,y=113,z=8,distance=..10,gamemode=adventure,advancements={luigis_mansion:key/parlor=true}] run function luigis_mansion:rooms/unlock_doors/parlor
execute if entity @s[x=684,y=113,z=1,distance=..10,gamemode=adventure,advancements={luigis_mansion:key/anteroom=true}] run function luigis_mansion:rooms/unlock_doors/anteroom
execute if entity @s[x=702,y=113,z=18,distance=..10,gamemode=adventure,advancements={luigis_mansion:key/small_hallway=true}] run function luigis_mansion:rooms/unlock_doors/small_hallway
execute if entity @s[x=698,y=113,z=55,distance=..10,gamemode=adventure,advancements={luigis_mansion:key/master_bedroom=true}] run function luigis_mansion:rooms/unlock_doors/master_bedroom
execute if entity @s[x=705,y=113,z=44,distance=..10,gamemode=adventure,advancements={luigis_mansion:key/nursery=true}] run function luigis_mansion:rooms/unlock_doors/nursery
execute if entity @s[x=706,y=103,z=8,distance=..10,gamemode=adventure,advancements={luigis_mansion:key/main_hallway=true}] run function luigis_mansion:rooms/unlock_doors/main_hallway
execute if entity @s[x=691,y=103,z=-11,distance=..10,gamemode=adventure,advancements={luigis_mansion:key/ball_room=true}] run function luigis_mansion:rooms/unlock_doors/ball_room
execute if entity @s[x=683,y=103,z=-38,distance=..10,gamemode=adventure,advancements={luigis_mansion:key/storage_room=true}] run function luigis_mansion:rooms/unlock_doors/storage_room
execute if entity @s[x=706,y=103,z=-16,distance=..10,gamemode=adventure,advancements={luigis_mansion:key/fortune_tellers_room=true}] run function luigis_mansion:rooms/unlock_doors/fortune_tellers_room
execute if entity @s[x=702,y=103,z=39,distance=..10,gamemode=adventure,advancements={luigis_mansion:key/laundry_room=true}] run function luigis_mansion:rooms/unlock_doors/laundry_room
execute if entity @s[x=664,y=103,z=14,distance=..10,gamemode=adventure,advancements={luigis_mansion:key/conservatory=true}] run function luigis_mansion:rooms/unlock_doors/conservatory
execute if entity @s[x=691,y=103,z=-3,distance=..10,gamemode=adventure,advancements={luigis_mansion:key/dinning_room=true}] run function luigis_mansion:rooms/unlock_doors/dinning_room
execute if entity @s[x=653,y=103,z=21,distance=..10,gamemode=adventure,advancements={luigis_mansion:key/courtyard=true}] run function luigis_mansion:rooms/unlock_doors/courtyard
execute if entity @s[x=653,y=103,z=-41,distance=..10,gamemode=adventure,advancements={luigis_mansion:key/rec_room=true}] run function luigis_mansion:rooms/unlock_doors/rec_room
execute if entity @s[x=668,y=103,z=-18,distance=..10,gamemode=adventure,advancements={luigis_mansion:key/main_stairs=true}] run function luigis_mansion:rooms/unlock_doors/main_stairs
execute if entity @s[x=672,y=103,z=19,distance=..10,gamemode=adventure,advancements={luigis_mansion:key/billiards_room=true}] run function luigis_mansion:rooms/unlock_doors/billiards_room
execute if entity @s[x=705,y=113,z=33,distance=..10,gamemode=adventure,advancements={luigis_mansion:key/twins_room=true}] run function luigis_mansion:rooms/unlock_doors/twins_room
execute if entity @s[x=706,y=123,z=-23,distance=..10,gamemode=adventure,advancements={luigis_mansion:key/safari_room=true}] run function luigis_mansion:rooms/unlock_doors/safari_room
execute if entity @s[x=683,y=123,z=-12,distance=..10,gamemode=adventure,advancements={luigis_mansion:key/balcony_2=true}] run function luigis_mansion:rooms/unlock_doors/balcony_2
execute if entity @s[x=683,y=123,z=27,distance=..10,gamemode=adventure,advancements={luigis_mansion:key/attic_hallway_2=true}] run function luigis_mansion:rooms/unlock_doors/attic_hallway_2
execute if entity @s[x=698,y=93,z=-28,distance=..10,gamemode=adventure,advancements={luigis_mansion:key/breaker_room=true}] run function luigis_mansion:rooms/unlock_doors/breaker_room
execute if entity @s[x=706,y=93,z=-28,distance=..10,gamemode=adventure,advancements={luigis_mansion:key/cellar=true}] run function luigis_mansion:rooms/unlock_doors/cellar
execute if entity @s[x=698,y=123,z=-2,distance=..10,gamemode=adventure,advancements={luigis_mansion:key/clockwork_room=true}] run function luigis_mansion:rooms/unlock_doors/clockwork_room
execute if entity @s[x=712,y=123,z=33,distance=..10,gamemode=adventure,advancements={luigis_mansion:key/armory=true}] run function luigis_mansion:rooms/unlock_doors/armory
execute if entity @s[x=692,y=93,z=-15,distance=..10,gamemode=adventure,advancements={luigis_mansion:key/pipe_room=true}] run function luigis_mansion:rooms/unlock_doors/pipe_room
execute if entity @s[x=712,y=93,z=-15,distance=..10,gamemode=adventure,advancements={luigis_mansion:key/cold_storage=true}] run function luigis_mansion:rooms/unlock_doors/cold_storage
execute if entity @s[x=706,y=113,z=-16,distance=..10,gamemode=adventure,advancements={luigis_mansion:key/sitting_room=true}] run function luigis_mansion:rooms/unlock_doors/sitting_room
execute if entity @s[x=693,y=123,z=-18,distance=..10,gamemode=adventure,advancements={luigis_mansion:key/artist_studio=true}] run function luigis_mansion:rooms/unlock_doors/artist_studio
execute if entity @s[x=654,y=93,z=-19,distance=..10,gamemode=adventure,advancements={luigis_mansion:key/secret_altar=true}] run function luigis_mansion:rooms/unlock_doors/secret_altar
