scoreboard players add @s Dialog 1
execute if entity @s[scores={Dialog=1}] run tellraw @a[tag=single] {"translate":"chat.type.text","with":[{"translate":"luigis_mansion:entity.e_gadd"},{"translate":"luigis_mansion:message.e_gadd.underground_lab.boos_released.1","with":[{"selector":"@a[gamemode=adventure]"}]}]}
execute if entity @s[scores={Dialog=1}] run tellraw @a[tag=more] {"translate":"chat.type.text","with":[{"translate":"luigis_mansion:entity.e_gadd"},{"translate":"luigis_mansion:message.e_gadd.underground_lab.boos_released.1.more"}]}
execute if entity @s[scores={Dialog=1}] run tellraw @a[tag=even_more] {"translate":"chat.type.text","with":[{"translate":"luigis_mansion:entity.e_gadd"},{"translate":"luigis_mansion:message.e_gadd.underground_lab.boos_released.1.more"}]}
execute if entity @s[scores={Dialog=64}] run tellraw @a {"translate":"chat.type.text","with":[{"translate":"luigis_mansion:entity.e_gadd"},{"translate":"luigis_mansion:message.e_gadd.underground_lab.boos_released.2"}]}
execute if entity @s[scores={Dialog=152}] run tellraw @a {"translate":"chat.type.text","with":[{"translate":"luigis_mansion:entity.e_gadd"},{"translate":"luigis_mansion:message.e_gadd.underground_lab.boos_released.3"}]}
execute if entity @s[scores={Dialog=336}] run tellraw @a {"translate":"chat.type.text","with":[{"translate":"luigis_mansion:entity.e_gadd"},{"translate":"luigis_mansion:message.e_gadd.underground_lab.boos_released.4"}]}
execute if entity @s[scores={Dialog=544}] run tellraw @a {"translate":"chat.type.text","with":[{"translate":"luigis_mansion:entity.e_gadd"},{"translate":"luigis_mansion:message.e_gadd.underground_lab.boos_released.5"}]}
execute if entity @s[scores={Dialog=728}] run tellraw @a[tag=single] {"translate":"chat.type.text","with":[{"translate":"luigis_mansion:entity.e_gadd"},{"translate":"luigis_mansion:message.e_gadd.underground_lab.boos_released.6"}]}
execute if entity @s[scores={Dialog=728}] run tellraw @a[tag=more] {"translate":"chat.type.text","with":[{"translate":"luigis_mansion:entity.e_gadd"},{"translate":"luigis_mansion:message.e_gadd.underground_lab.boos_released.6.more"}]}
execute if entity @s[scores={Dialog=728}] run tellraw @a[tag=even_more] {"translate":"chat.type.text","with":[{"translate":"luigis_mansion:entity.e_gadd"},{"translate":"luigis_mansion:message.e_gadd.underground_lab.boos_released.6.more"}]}
execute if entity @s[scores={Dialog=920}] run tellraw @a[tag=single] {"translate":"chat.type.text","with":[{"translate":"luigis_mansion:entity.e_gadd"},{"translate":"luigis_mansion:message.e_gadd.underground_lab.boos_released.7"}]}
execute if entity @s[scores={Dialog=920}] run tellraw @a[tag=more] {"translate":"chat.type.text","with":[{"translate":"luigis_mansion:entity.e_gadd"},{"translate":"luigis_mansion:message.e_gadd.underground_lab.boos_released.7.more"}]}
execute if entity @s[scores={Dialog=920}] run tellraw @a[tag=even_more] {"translate":"chat.type.text","with":[{"translate":"luigis_mansion:entity.e_gadd"},{"translate":"luigis_mansion:message.e_gadd.underground_lab.boos_released.7.more"}]}
execute if entity @s[scores={Dialog=1072}] run tellraw @a {"translate":"chat.type.text","with":[{"translate":"luigis_mansion:entity.e_gadd"},{"translate":"luigis_mansion:message.e_gadd.underground_lab.boos_released.8"}]}
execute if entity @s[scores={Dialog=1216}] run tellraw @a[tag=single] {"translate":"chat.type.text","with":[{"translate":"luigis_mansion:entity.e_gadd"},{"translate":"luigis_mansion:message.e_gadd.underground_lab.boos_released.9","with":[{"selector":"@a[gamemode=adventure]"}]}]}
execute if entity @s[scores={Dialog=1216}] run tellraw @a[tag=more] {"translate":"chat.type.text","with":[{"translate":"luigis_mansion:entity.e_gadd"},{"translate":"luigis_mansion:message.e_gadd.underground_lab.boos_released.9.more"}]}
execute if entity @s[scores={Dialog=1216}] run tellraw @a[tag=even_more] {"translate":"chat.type.text","with":[{"translate":"luigis_mansion:entity.e_gadd"},{"translate":"luigis_mansion:message.e_gadd.underground_lab.boos_released.9.more"}]}
execute if entity @s[scores={Dialog=1392}] run tellraw @a[tag=single] {"translate":"chat.type.text","with":[{"translate":"luigis_mansion:entity.e_gadd"},{"translate":"luigis_mansion:message.e_gadd.underground_lab.boos_released.10"}]}
execute if entity @s[scores={Dialog=1392}] run tellraw @a[tag=more] {"translate":"chat.type.text","with":[{"translate":"luigis_mansion:entity.e_gadd"},{"translate":"luigis_mansion:message.e_gadd.underground_lab.boos_released.10.more"}]}
execute if entity @s[scores={Dialog=1392}] run tellraw @a[tag=even_more] {"translate":"chat.type.text","with":[{"translate":"luigis_mansion:entity.e_gadd"},{"translate":"luigis_mansion:message.e_gadd.underground_lab.boos_released.10.more"}]}
execute if entity @s[scores={Dialog=1648}] run give @a minecraft:???{luigis_mansion:{id:"luigis_mansion:boo_radar"},display:{Name:"{\"translate\":\"luigis_mansion:item.boo_radar\"}"}}
execute if entity @s[scores={Dialog=1648}] run tag @a add boos_released
tag @s[scores={Dialog=1648}] add boos_released
scoreboard players set @s[scores={Dialog=1648}] Dialog 0