scoreboard players add @s[scores={Dialog=..48}] Dialog 1
execute if entity @a[scores={EGadd=1},limit=1] run function luigis_mansion:dialog/e_gadd/underground_lab/mansion
execute if entity @a[scores={EGadd=2},limit=1] run function luigis_mansion:dialog/e_gadd/underground_lab/training
execute if entity @a[scores={EGadd=3},limit=1] run function luigis_mansion:dialog/e_gadd/underground_lab/gallery
execute if entity @a[scores={EGadd=4},limit=1] run function luigis_mansion:dialog/e_gadd/underground_lab/nowhere
execute if entity @s[scores={Dialog=1}] run tellraw @a[tag=single] {"translate":"chat.type.text","with":[{"translate":"luigis_mansion:entity.e_gadd"},{"translate":"luigis_mansion:message.underground_lab.e_gadd.re.1","with":[{"selector":"@a[gamemode=adventure]"}]}]}
execute if entity @s[scores={Dialog=1}] run tellraw @a[tag=more] {"translate":"chat.type.text","with":[{"translate":"luigis_mansion:entity.e_gadd"},{"translate":"luigis_mansion:message.underground_lab.e_gadd.re.1.more"}]}
execute if entity @s[scores={Dialog=1}] run tellraw @a[tag=even_more] {"translate":"chat.type.text","with":[{"translate":"luigis_mansion:entity.e_gadd"},{"translate":"luigis_mansion:message.underground_lab.e_gadd.re.1.more"}]}
execute if entity @s[scores={Dialog=48}] run tellraw @a {"translate":"luigis_mansion:message.underground_lab.e_gadd.re.click","color":"green","extra":[{"text":"\n"},{"translate":"luigis_mansion:message.underground_lab.e_gadd.re.mansion","clickEvent":{"action":"run_command","value":"/trigger EGadd set 1"}},{"text":"\n"},{"translate":"luigis_mansion:message.underground_lab.e_gadd.re.training","clickEvent":{"action":"run_command","value":"/trigger EGadd set 2"}},{"text":"\n"},{"translate":"luigis_mansion:message.underground_lab.e_gadd.re.gallery","clickEvent":{"action":"run_command","value":"/trigger EGadd set 3"}},{"text":"\n"},{"translate":"luigis_mansion:message.underground_lab.e_gadd.re.nowhere","clickEvent":{"action":"run_command","value":"/trigger EGadd set 4"}}]}
execute if entity @s[scores={Dialog=48}] run scoreboard players enable @a[gamemode=adventure] EGadd